---
title: "Modelos Lineales"
author: "Josue Jhonatan Colunche Vasquez"
format: html
---

#pasos para analisis de datos 

1. creacion de mi diseño experimental-modelo estadistico
2. coleccion de dtos 
3. importar y verificar los factores 
4. analisis de varianza 
5. comparacion de medias 
6. Graficos

# librerias 

```{r}
library(tidyverse) 
library(googlesheets4)
library(lme4)
library(emmeans)
```
# cargar base de datos 

https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=1263018298#gid=1263018298 

```{r}
url <- "https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=1263018298#gid=1263018298"

gs <- url %>%
      as_sheets_id()

fb <- gs %>%
      range_read("fb")%>%
      mutate(across(1:bloque, ~as.factor(.)))
  str(fb)
```


# Modelo 
$$  wue_{tuber}= \mu + bloque + riego + geno +riego*geno + e  $$

# Analisis de Varianza 

```{r}
md <- lmer(formula = twue ~ 0 + (1|bloque) + riego*geno
           , data = fb)

anova(md)
library(car)
Anova(md)
```






